Django/PycharmProject/BoardProject/boardRoot/board/urls.py
from django.contrib import admin
from django.urls import path, include
# 위에 , include 추가

urlpatterns = [     # admin으로 들어갈 수 있게 해줌
    path('admin/', admin.site.urls),
    # path('noticeboard/', include('noticeboard.urls') admin.site.urls),   # 전체 조회하게 만듬
    path('noticeboard/', include('noticeboard.urls'))
]
# 지금 이곳에 admin, noticeboard만 정의했으니, 그 둘만 접속 가능함.

Django/PycharmProject/BoardProject/boardRoot/noticeboard/urls.py
from django.urls import path
from . import views
# .  <-  현재의(=notiecboard)

app_name = 'noticeboard'
urlpatterns = [
    path('', views.index, name='index'),  # 주소는 'index'라는 이름으로 됨
    #  views의 index란 함수를 호출
    path('write/', views.write_article, name='write_article'),  # / 추가
    # write_artice 라는 이름으로 만들 것
    # view 가서 def write_article(request) -> 만들어줘야 됨
    path('add/', views.add_article, name='add_article'),        #  / 추가
    path('<int:article_id>/', views.view_article, name='view'),
    # 요 슬래시/  자동으로 붙지만, 명시적으로 써줍시다.
    # 이러면 noticecode/id번호 가 됨
    # 넘어온 값을 article_id 에 담은 것
    # 다음엔 views.add_article을 만듭시다. -> views.py로 이동

    path('update/<int:article_id>/', views.update_article, name='update'),
    path('delete/<int:article_id>/', views.delete_article, name='delete'),
]

Django/PycharmProject/BoardProject/boardRoot/noticeboard/models.py
from django.db import models
from django.utils.timezone import now
# Create your models here.
class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    writeDate = models.DateTimeField(default=now, editable=False)
    writeID = models.CharField(max_length=50)

    def __str__(self):
        return self.title

Django/PycharmProject/BoardProject/boardRoot/noticeboard/views.py

from django.shortcuts import render, get_object_or_404   # get_object_or_404 추가.  view_article(리퀘,id)작업중
from noticeboard.models import Notice
from django.http import HttpResponseRedirect  # 이것과 아래것 2개 추가
from django.urls import reverse
from django.utils import timezone  # 타임존 추가
# Create your views here.


def index(request):  # request -> 사용자가 요청한 request객체를 받음 -> Django가 알아서 전달해줌
    # 전체를 보여달라는 요청이므로, 모든 데이터를 가져와야함. 가져와서 변수에 담아야 함. 변수의 이름=article_list
    article_list = Notice.objects.all().order_by('-writeDate')  # - 붙이면 디센딩, 안붙이면 어센딩
                                        # 일반적으로 게시글 가장 최근이 가장 위에 오기때문에 이렇게 한것
    # 변수 설정. 마음대로 -> 여기선 context
    context = {'article_list': article_list}  # 파이썬 dictionary 만들어줌 -> return해서 클라이언트에게 던져줌
    # 데이터만 던져주면 소용 없음, HTML낑겨서 전체 전달해야함. -> HTML소스 아직 없음. -> 있어야 return 쓸 수 있음.
    # 당장 HTML부터 만들어야함,.
    # return ''

    # MVT 중에서 M(모델), V(뷰) 는 했음 , T(템플릿) 해야함

    # html 만들었다고 가정하고(boardRoot\templates\noticeboard\index.html) 이제 return 마무리
    # import render 에 render 들어있음.
    return render(request, 'noticeboard/index.html', context) # 사용자에게 보내져야할 html 파일
    # 보낼때, context도 같이 보내라.
    # noticeboard로 들어올때, index.html 을 보여준다는 뜻.


def write_article(request):
    return render(request, 'noticeboard/writeArticle.html')
# 색을 작성하는거니 넘겨줄 데이터 필요 없음. 이거면 됨
# templates -> noticeboard  우클릭 -> writeArticle.html 파일 생성


def add_article(request):  # from에서 뽑아오기 위한 함수
    notice = Notice()
    notice.title = request.POST['title']
    notice.content = request.POST['content']
# writeAtricl 의 30번째줄,  name="content 이므로
    notice.writeID = 'bit'
    notice.save()

    return HttpResponseRedirect(reverse('noticeboard:index'))
    # 요 주소로 호출해 라고 호출하는게 Redirect -> 주소, 욜로 리다이렉트 해
# -> 템플릿을 리다이렉트한것, 소스 안바꾸려고. {% url~~ %}  <-  똑같은 기능을 하는 파이썬 함수가 필요하다 -> 그게 리버스
    # 위의 리버스 저놈이 이 기능을 한다는 것


def view_article(request, article_id):  # article_id  ->  이름이 같으면 장고가 알아서 받아서 값을 넘겨줌
    notice = get_object_or_404(Notice, pk=article_id)  # 위의 article_id를 굉장히 쉽게 넘겨받음
    # -> 받고 렌더시키면 됨
    return render(request, 'noticeboard/detail.html', {'article':notice})  # 위의 notice를 항상 dictionary타입으로 넘겨줘야함.
# 그리고 우린 detail.html을 만들면 되는거야. -> 일단 껍데기만 만들자
# -> templates -> noticeboard 우클릭 -> detail.html 만들기


def update_article(request, article_id):
    notice = Notice.objects.get(id=article_id)
    if request.method == 'POST':
        notice.title = request.POST['title']
        notice.content = request.POST['content']
        notice.writeDate = timezone.datetime.now()
        notice.save()
        return HttpResponseRedirect(reverse('noticeboard:view', args=(article_id,)))
    else:
        return render(request, 'noticeboard/detail.html', {'article': notice})


def delete_article(request, article_id):
    # pass
    notice = Notice.objects.get(id=article_id)
    notice.delete()
    return HttpResponseRedirect(reverse('noticeboard:index'))


# 파이참은 함수와 함수 사이 최소 2줄을 띄워야 빨간줄이 안그어짐

Django/PycharmProject/BoardProject/boardRoot/templates/noticeboard/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>글보기</title>
    <style>
        #tr_btn_modify {
            display: none;
        }
    </style>
    <script>
        function backToList(obj) {
            obj.action = "{% url 'noticeboard:index' %}";
            obj.submit();
        }

        function fn_enable(obj) {
            document.querySelector('#i_title').disabled = false;
            document.querySelector('#i_content').disabled = false;
            document.querySelector('#tr_btn_modify').style.display = "block";
            document.querySelector('#tr_btn').style.display = "none";
        }

        function fn_modify_article(obj) {
            obj.action = "{% url 'noticeboard:update' article.id %}";
            obj.submit();
        }

        function fn_remove_article(obj) {
            obj.action = "{% url 'noticeboard:delete' article.id %}";
            obj.submit();
        }
    </script> <!-- 위의 disabled=false -> 보이게 만듬   /  none -> 감춰버리겠다  -->
</head>
<body>
    <form name="frmArticle" method="post">
        {% csrf_token %}
        <table borde="0" align="center">
            <tbody>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">글번호</td>  <!-- 글 번호 하나씩 찍기 -->
                    <td><input type="text" value="{{article.id}}" disabled></td>
                    <!-- Django에서 변수 쓸떄는 중괄호2개로 감싸라고 했음 -->
                                            <!-- disabled로 막아둘것 -->
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">작성자ID</td>
                    <td><input type="text" value="{{article.writeID}}" name="writer" disabled></td> <!-- 이름 주가해줄것 -->
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">제목</td>
                    <td><input type="text" value="{{article.title}}" name="title" id="i_title" disabled></td>  <!--여기에 제목속성, id속성 추가함-->
                </tr>
                <tr>
                    <td width="150" align="center" bgcolor="#FF9933">내용</td> <!--내용은 여러줄 나오는거기 때문에 textarea로 해줌-->
                    <td><textarea rows="20" cols="60" name="content" id="i_content" disabled>
                        {{article.content}}</textarea></td>  <!--textarea 초기 줄은 20줄로-->
                </tr>
            <tr>
                <td width="20%" align="center" bgcolor="#FF9933">등록일자</td>
                <td><input type="text" value="{{article.writeDate}}" disabled></td>  <!--작성일자니까 writeDate-->
            </tr>
            <tr id="tr_btn_modify">
                <td colspan="2" align="center">
                    <input type="button" value="수정반영하기" onclick="fn_modify_article(frmArticle)">
                    <input type="button" value="취소" onclick="backToList(frmArticle)">
                </td>
            </tr>
            <tr id="tr_btn">
                <td colspan="2" align="center">
                    <input type="button" value="수정하기" onclick="fn_enable(frmArticle)">
                    <input type="button" value="삭제하기" onclick="fn_remove_article(frmArticle)">
                    <input type="button" value="리스트로 돌아가기" onclick="backToList(frmArticle)">
                </td>
            </tr>
            </tbody>
        </table>
    </form>
</body>
</html>

Django/PycharmProject/BoardProject/boardRoot/templates/noticeboard/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>게시글 목록</title>
    <style>
        .cls1 {
            text-decoration: none;
        }
        .cls2 {
            text-align: center;
            font-size: 30px;
            display: block;
        }
    </style>
</head>
<body>
    <table align="center" border="1" width="80%">
        <thead> <!-- 테이블 헤드 -->
            <tr height="10" align="center" bgcolor="lightgreen">
                <th>글번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>
        <!-- 템플릿 렝기지 쓰는 방법 -->
        <!-- noticeboard의 views.py 안의 context = {'article_list': article_list} 부분에서 -->
        {% if article_list %}  <!-- article_list 키 이름으로 데이터가 존재하면 -->
        <tbody>
            {% for article in article_list %}   <!-- articel -> 하나의 게시물 -->
                <tr align="center">  <!-- 글번호, 작성자, 제목, 작성일 -> 4개가 들어가야함 -->
                    <!-- 1. 글번호 -->
                    <td width="5%">{{forloop.counter}}</td> <!--횟수 숫자로 나오는 이곳의 특별한 문법-->
                                   <!-- 중괄호 2번 쓰면 장고가, 아 얘는 변수구나 라고 인식함 -->
                    <!-- 2. 작성자 -->
                    <!-- article이 하나의 게시물이므로 -->
                    <td width="10%">{{article.writeID}}</td>
                    <!-- 3. 제목 -->
                    <td align="left" width="35%">
                        <span style="padding-right:30px"></span>
                        <a class="cls1" href="{% url 'noticeboard:view' article.id %}">{{article.title}}</a><!-- 글제목 -->
                    </td>
                    <!-- 4. 작성일 -->
                    <td width="10%">{{article.writeDate}}</td>
                </tr>
            {% endfor %}  <!-- 반드시 이게 들어감, 이 사이에 적어주면 됨 -->
        </tbody>
        {% else %}  <!-- 만약에 데이터가 없으면 -->
        <tbody>
            <tr height="10">
                <td colspan="4">
                    <p align="center">  <!-- <b>->bold=굵게 -->
                        <b><span style="font-size:15pt;">등록된 글이 없습니다</span></b>
                    </p>
                </td>
            </tr>
        </tbody>
        {% endif %}
        <!-- 이것은 주석 -->
    </table>

    <!-- table이 끝나는 이지점에 앵커테이블 하나 넣어줄거. -> 새글쓰기 누르면 바로 가게 만들것. -->
    <!-- <a class="cls1" href="write"> <-  일일이 하나씩 다 넣어주면 나중에 못찾음 -->
    <a class="cls1" href="{% url 'noticeboard:write_article' %}">
        <!-- 콜론 기준으로 왼쪽은 noticeboard의 app_name = 'noticeboard', 오른쪽은     path('write', views.write_article, name='write_article') -->
        <!-- 주소체계를 바꾸고싶으면  noticeboard/urls만 바꾸면 됨-->
        <span class="cls2">글쓰기</span>
    </a>
</body>
</html>

Django/PycharmProject/BoardProject/boardRoot/templates/noticeboard/writeArticle.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>새글 쓰기</title>
    <script>
        function backToList(obj) {
            obj.action="{% url 'noticeboard:index' %}";
            obj.submit();
        }
    </script>
</head>
<body>
    <h1 style="text-align:center">새글 쓰기</h1>
    <form name="articleForm" method="post" action="{% url 'noticeboard:add_article' %}">  <!-- action -> 어디로 보낼건가 -->
                                                <!-- add_article로 내용이 전손됨 -->
        <!-- Django에서 만드시 해야하는 것 -> csrf = 내용을 가로채서 내용을 바꿔서 보내줌. -> 정보 원하는대로 보내줘서 해킹당함
        그래서 식별을 해줘야 함.
        장고에서 자기가 갖고있는 토큰을 보냄. 그래서 받을때, 이 토큰과 같은지 확인함.
        클라이언트에서 이 토큰을 어떻게 보내느냐. -> 다음을 쓰면 됨 -->
    {% csrf_token %}  <!-- form 제일 상단에, 반드시 얘를 써줄 것 -->
        <table boder="0" align="center">
            <tr>
                <td align="right">글제목:</td>
                <td colspan="2"><input type="text" size="71" maxlength="100" name="title" /></td>
                        <!-- 아까 models.py 에서 maxlength 100으로 했으니 100 넘으면 안됨 -->
            </tr>
            <tr>
                <td align="right" valign="top"><br>글내용:</td>
                <td colspan="2"><textarea name="content" rows="10" cols="65" maxlength="2000">
                </textarea></td>
            </tr>
            <tr>
                <td align="right"></td>
                <td colspan="2"><input type="submit" value="글쓰기"/>
                <input type="button" value="목록보기" onclick="backToList(this.form)"/></td>  <!-- 취소하고 목록으로 돌아가기 -->
            </tr>
        </table>
    </form>
</body>
</html>